### ISSUE TITLE
Remove all Firebase integrations and replace with local caches

### ISSUE THREAD

**Issue by alecgorge** [RelistenNet/relisten-ios#10]
As it says in the title. Closes #9.

We need to eliminate Firebase and come up with a better way for users to manage things.

**Comment by alecgorge** [comment]
Sketch of an idea:

* Users sign in with a phone number and are texted a password (thanks @switz!)
* Users are stored as `(user_id, phone_number, last_login, logins_in_last_five_minutes, login_timeout, login_code)`
* Favorite shows are maintained as a `(user_id, artist_id, show_display_date, created_at)` table
* Favorite artists are maintained as a `(user_id, artist_id, created_at)`
* Playlists are maintained as `(user_id, title, is_public)` + `(playlist_id, artist_id, mp3_url)`

**Comment by farktronix** [comment]
I second the vote to remove Firebase and store things locally for now.

I'd vote for using CloudKit for server persistence of this data. Most people have an iCloud account logged in (iOS makes it really difficult to not set one up on install/upgrade these days)

Even if you'd like to store the data on the relisten.live servers, you could use the CloudKit user identifier in place of a phone number and then you wouldn't have to do any sign in/set up (it would also avoid any potential SMS costs if you use phone numbers for verification)

**Comment by farktronix** [comment]
(I'm of course extremely biased towards CloudKit after having worked on it at Apple, so feel free to take that all with a grain of salt 😉)
