### ISSUE TITLE
Freeze then crash when popping ASViewControllers

### ISSUE THREAD

**Issue by lukeswitz** [RelistenNet/relisten-ios#173]
When using the app and navigating from one list to the next moving backwards, the app hangs with the audio session active. It’s possible to play music from another app when this crash happens, meaning the AVAudioSession isn’t being cleaned up. 

Will dig into this when have the weekend to debug. Cheers. 

Builds tested: latest iOS & TestFlight
Devices: iPhone 6s/8 12.4 & iOS 13b06

**Comment by alecgorge** [comment]
I have seen reports of people with particularly large libraries experiencing freezes when selecting a new song, but not when navigating forward/back or during the rest of playback.

In those cases though, the app doesn't crash and audio does play but the CPU is pegged for ~15 seconds.

I wonder if these are related.

**Comment by lukeswitz** [comment]
Looking into it now. A mess of framework imports here. I might just start fresh without all this baggage and write a ‘lite’ version. I’m surprised this even ran on my phone.

**Comment by lukeswitz** [comment]
Entire use of most design patterns and iOS functions are deprecated. Will report back with some positive news.
