### ISSUE TITLE
Need small SBD icon for compact album arts

### ISSUE THREAD

**Issue by alecgorge** [RelistenNet/relisten-ios#69]
Probably about 1/2 the size

**Comment by farktronix** [comment]
The downloaded icon is also pretty hard to see. Adding a blur or a shadow behind it should help it stand out.

**Comment by alecgorge** [comment]
@farktronix i think the fix for that will be making the arrow part have a white background instead of being transparent. i think we can cut that for 4.0. for now, the visual aberration in the bottom left can indicate that it is available offline haha

**Comment by farktronix** [comment]
That's a great idea, and it solves the download icon problem!

<img width="356" alt="screen shot 2018-08-26 at 14 12 53" src="https://user-images.githubusercontent.com/4943/44633032-2f350000-a93a-11e8-8007-a0ccafcc7bf9.png">
