### ISSUE TITLE
Utilize Crashlytics logging instead of print statements

### ISSUE THREAD

**Issue by alecgorge** [RelistenNet/relisten-ios#79]
https://docs.fabric.io/apple/crashlytics/enhanced-reports.html#custom-logging

We should also update AGAudioPlayer/BASS gapless to support a custom logging callback function to track all of this.

**Comment by alecgorge** [comment]
This looks like a good way to centralize logging: https://github.com/emaloney/CleanroomLogger

`os_log` seems like a disaster for us: no way to collect anything after it is sent

**Comment by farktronix** [comment]
[CleanroomLogger #69](https://github.com/emaloney/CleanroomLogger/issues/69)
> For all those reasons and many more that I could expound upon at great length, I will never be adding Cocoapods support to this or any other project I maintain.
>
>This decision is final and will not be revisited. If this rules out CleanroomLogger for you, then I'm sorry this package couldn't meet your needs; I hope you can find one that does.

There are a ton of forks of the project to add a Podspec. I don't see one that appears to be long lived and maintaining a Podspec though. [This](https://github.com/500px/CleanroomLogger) is the longest lived fork that I could easily find, so I guess we can go with that and make our own fork later if necessary.
