### ISSUE TITLE
Recent tracks JSON quickly exceeds the Firestore document size limit

### ISSUE THREAD

**Issue by farktronix** [RelistenNet/relisten-ios#9]
I noticed that my recent tracks were disappearing shortly after they were played. They'd show up in the recent tracks view, but then they'd disappear a few seconds later.

I finally chased this down to Firestore refusing the save of the library and silently reverting back to the server's data:

```
2018-07-09 16:14:10.387710-0700 Relisten[10129:315605] 5.0.0 - [Firebase/Firestore][I-FST000001] FSTWriteStream 0x60800011a280 close: Error Domain=FIRFirestoreErrorDomain Code=3 "A document cannot be written because it exceeds the maximum size allowed."
```

I just have 12 recently played tracks, but it looks like the JSON for each track is pretty big, since it contains all of the artist/show/source information, including every track in the show. Those 12 tracks end up being over 1MB of JSON data.

**Comment by farktronix** [comment]
A simple way to fix this would be to just store the recent track IDs in Firestore, then re-fetch their info from the relisten.live API when the library is updated. I'm going to look into doing that.

**Comment by alecgorge** [comment]
> A simple way to fix this would be to just store the recent track IDs in Firestore, then re-fetch their info from the relisten.live API when the library is updated. I'm going to look into doing that.

Unfortunately I didn't do this on purpose. Track IDs are not persistent in the database (eg: show gets reindexed with new track information). The MP3 track url is a viable non-transient key but tracks sometime get removed. I don't really have a super way of handling this.

I don't want to be responsible for storing user information in our hosted db and making the content database fully persistent would mean much, much more complicated scrapers. In addition, I wouldn't be able to rebuild the whole database from scratch without an issue. Backups, and security would become much, *much* more important and I'm not sure that would be a great use of time.

We could make an API route that does bulk lookups by mp3 urls, but that would require roundtrips for recently played (and probably another caching layer) and would make adding features like playlists more complex on that end. On the other hand, it would make it a lot easier on the Firebase end. We could also use the Firebase API and bake functionality into the server

No matter what we do, it is clear that this is a showstopper for now. I'd love to hear everyone's thoughts though.
